GET http://localhost:8080/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTc2MzgxMjk2NH0.1fbOFg_p3YpKwU9PJCi-4KtKjItOfHxWAbwBahnHQ6M

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Raul",
  "email": "raul@email.com",
  "password": "123"
}

###
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "raul@email.com",
  "password": "123"
}
