GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Raul",
  "email": "raul@email.com",
  "password": "123"
}

###
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "raul@email.com",
  "password": "123"
}
