GET http://localhost:8080/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImV4cCI6MTc2MzgyMDc1N30.7GwiRidDhsTegfhLKWXk3o1Pk_p98JxRPhIIdS_2BZk

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Raul",
  "email": "raul@email.com",
  "password": "123"
}

###
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "eduardo@email.com",
  "password": "123"
}
